### PR TITLE
Add test for unpacking in for loop.

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Add a test for #61.

Still requires the fix to be added.

### CODE REVIEW

**Comment by Tadaboody** [comment]
Thank you so much! I'll look into this

**Comment by Dreamsorcerer** [comment]
Curiously, in my own code, this breaks:
`for inst, aliases in updates:`
But, this works fine:
`for i, hit in enumerate(index.browse_objects(algolia_params)):`

**Comment by Dreamsorcerer** [comment]
Any luck? This completely breaks flake8 for us.

**Comment by Tadaboody** [comment]
@Dreamsorcerer Hey! I've pushed a fix to this branch, it passes the test but do you mind running it against your code?

**Comment by Dreamsorcerer** [comment]
Confirmed. No exceptions when running acroos the code base.

**Pull request merged**
